name: server
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/matheusoreis/flame-multiplayer

environment:
  sdk: ^3.6.1

dependencies:
  sqlite3: ^2.7.2
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
